### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by mosemister** [ACMWTeam/Core#1]
- [ ] room boundaries
- [ ] Room locks
- [ ] Room area named Suites
- [ ] Room area named Regular Cabin
- [ ] Room area named Accompany Cabin
- [ ] Room area named Balcony Cabin
- [ ] General rank named VIP
- [ ] Generial rank named Platinum
- [ ] General rank named Standard
- [ ] VIP has choice of a free Suite, Regular cabin, Accompany Cabin or Balcony cabin
- [ ] Remove player from room after 90 days from room if VIP rank
- [ ] Remove player from room after 60 days from room if Platinum rank
- [ ] Remove player from room after 30 days from room if Standard rank
- [ ] Rooms open if player hits door and/or linked sign with keycard
- [ ] Gui shop
- [ ] Gui shop connected to Chest
- [ ] Confirmation for purchase
-[ ]
